"""add_blacklisted_tokens_table

Revision ID: 53ca64f148e1
Revises: eadc0c47f2d9
Create Date: 2026-05-20 11:06:59.683626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ca64f148e1'
down_revision: Union[str, None] = 'eadc0c47f2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
